CREATE TABLE universities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    address VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE boarding_stops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local VARCHAR(255) UNIQUE
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    phone VARCHAR(255) UNIQUE,
    active BOOLEAN NOT NULL,
    role VARCHAR(30) NOT NULL,
    CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'STUDENT', 'CONDUCTOR'))
);

CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate VARCHAR(255) NOT NULL UNIQUE,
    capacity INTEGER NOT NULL
);

CREATE TABLE conductors (
    user_id BIGINT PRIMARY KEY,
    license VARCHAR(255) NOT NULL,
    license_expiration_date DATE NOT NULL,
    CONSTRAINT fk_conductors_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE students (
    user_id BIGINT PRIMARY KEY,
    period BIGINT NOT NULL,
    course VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    university_id BIGINT NOT NULL,
    preferred_boarding_stop_id BIGINT,
    CONSTRAINT fk_students_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_students_university FOREIGN KEY (university_id) REFERENCES universities(id),
    CONSTRAINT fk_students_preferred_stop FOREIGN KEY (preferred_boarding_stop_id) REFERENCES boarding_stops(id)
);

CREATE TABLE interest_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_date DATE NOT NULL,
    closing_time TIME,
    departure_time TIME NOT NULL,
    arrival_time TIME NOT NULL,
    return_departure_time TIME NOT NULL,
    return_arrival_time TIME NOT NULL,
    destination_id BIGINT NOT NULL,
    list_status VARCHAR(30) NOT NULL,
    CONSTRAINT interest_lists_list_status_check CHECK (list_status IN ('OPEN', 'PROCESSING', 'CLOSED')),
    CONSTRAINT fk_interest_lists_destination FOREIGN KEY (destination_id) REFERENCES universities(id)
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    interest_list_id BIGINT NOT NULL,
    booking_status VARCHAR(30) NOT NULL,
    trip_type VARCHAR(30) NOT NULL,
    destination_id BIGINT NOT NULL,
    boarding_location_id BIGINT NOT NULL,
    CONSTRAINT uk_booking_student_interestlist UNIQUE (student_id, interest_list_id),
    CONSTRAINT bookings_booking_status_check CHECK (booking_status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT bookings_trip_type_check CHECK (trip_type IN ('OUTBOUND', 'INBOUND', 'ROUND_TRIP')),
    CONSTRAINT fk_bookings_student FOREIGN KEY (student_id) REFERENCES students(user_id),
    CONSTRAINT fk_bookings_interest_list FOREIGN KEY (interest_list_id) REFERENCES interest_lists(id),
    CONSTRAINT fk_bookings_destination FOREIGN KEY (destination_id) REFERENCES universities(id),
    CONSTRAINT fk_bookings_boarding_stop FOREIGN KEY (boarding_location_id) REFERENCES boarding_stops(id)
);

CREATE TABLE trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interest_list_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    conductor_id BIGINT,
    vehicle_id BIGINT,
    CONSTRAINT trips_trip_status_check CHECK (status IN ('PROCESSING', 'SCHEDULED', 'STARTED', 'COMPLETED')),
    CONSTRAINT fk_trips_interest_list FOREIGN KEY (interest_list_id) REFERENCES interest_lists(id),
    CONSTRAINT fk_trips_conductor FOREIGN KEY (conductor_id) REFERENCES conductors(user_id),
    CONSTRAINT fk_trips_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
);

CREATE TABLE trip_students (
    trip_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    PRIMARY KEY (trip_id, student_id),
    CONSTRAINT fk_trip_students_trip FOREIGN KEY (trip_id) REFERENCES trips(id),
    CONSTRAINT fk_trip_students_student FOREIGN KEY (student_id) REFERENCES students(user_id)
);

CREATE TABLE trip_interest_lists (
    trip_id BIGINT NOT NULL,
    interest_list_id BIGINT NOT NULL,
    PRIMARY KEY (trip_id, interest_list_id),
    CONSTRAINT fk_trip_interest_lists_trip FOREIGN KEY (trip_id) REFERENCES trips(id),
    CONSTRAINT fk_trip_interest_lists_interest_list FOREIGN KEY (interest_list_id) REFERENCES interest_lists(id)
);

CREATE TABLE trip_boarding_points (
    trip_id BIGINT NOT NULL,
    boarding_stop_id BIGINT NOT NULL,
    PRIMARY KEY (trip_id, boarding_stop_id),
    CONSTRAINT fk_trip_boarding_points_trip FOREIGN KEY (trip_id) REFERENCES trips(id),
    CONSTRAINT fk_trip_boarding_points_stop FOREIGN KEY (boarding_stop_id) REFERENCES boarding_stops(id)
);

CREATE TABLE trip_stop_points (
    trip_id BIGINT NOT NULL,
    university_id BIGINT NOT NULL,
    PRIMARY KEY (trip_id, university_id),
    CONSTRAINT fk_trip_stop_points_trip FOREIGN KEY (trip_id) REFERENCES trips(id),
    CONSTRAINT fk_trip_stop_points_university FOREIGN KEY (university_id) REFERENCES universities(id)
);
