package com.guilhermesemog.unimove.service;

import com.guilhermesemog.unimove.dto.recurrence.RecurrenceOccurrenceResponse;
import com.guilhermesemog.unimove.dto.recurrence.RecurrencePlanRequest;
import com.guilhermesemog.unimove.dto.recurrence.RecurrencePreviewResponse;
import com.guilhermesemog.unimove.model.InterestList;
import com.guilhermesemog.unimove.model.RecurrencePlan;
import com.guilhermesemog.unimove.model.enums.RecurrenceOccurrenceAction;
import com.guilhermesemog.unimove.repository.InterestListRepository;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.time.Clock;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Set;
import java.util.UUID;

@Component
public class RecurrencePlanningEngine {
    private final InterestListRepository interestListRepository;
    private final Clock businessClock;
    private final int defaultHorizonWeeks;

    public RecurrencePlanningEngine(
            InterestListRepository interestListRepository,
            Clock businessClock,
            @Value("${unimove.phase-five.recurrence.default-horizon-weeks:8}") int defaultHorizonWeeks
    ) {
        this.interestListRepository = interestListRepository;
        this.businessClock = businessClock;
        this.defaultHorizonWeeks = defaultHorizonWeeks;
    }

    public RecurrencePreviewResponse preview(RecurrencePlanRequest request, UUID planId) {
        int horizonWeeks = request.horizonWeeks() == null ? defaultHorizonWeeks : request.horizonWeeks();
        return calculate(
                request.destinationId(), request.daysOfWeek(), request.startDate(), request.endDate(),
                horizonWeeks, planId
        );
    }

    public RecurrencePreviewResponse preview(RecurrencePlan plan) {
        return calculate(
                plan.getDestination().getId(), plan.getDaysOfWeek(), plan.getStartDate(), plan.getEndDate(),
                plan.getHorizonWeeks(), plan.getId()
        );
    }

    public LocalDate firstEligibleDate(LocalDate from, LocalDate end, Set<DayOfWeek> days) {
        LocalDate candidate = from;
        while (!candidate.isAfter(end)) {
            if (days.contains(candidate.getDayOfWeek())) return candidate;
            candidate = candidate.plusDays(1);
        }
        return null;
    }

    private RecurrencePreviewResponse calculate(
            UUID destinationId,
            Set<DayOfWeek> days,
            LocalDate startDate,
            LocalDate endDate,
            int horizonWeeks,
            UUID planId
    ) {
        LocalDate today = LocalDate.now(businessClock);
        LocalDate rangeStart = startDate.isAfter(today) ? startDate : today;
        LocalDate horizonEnd = today.plusWeeks(horizonWeeks);
        LocalDate rangeEnd = endDate.isBefore(horizonEnd) ? endDate : horizonEnd;
        if (rangeStart.isAfter(rangeEnd)) {
            return new RecurrencePreviewResponse(rangeStart, rangeEnd, 0, 0, 0, List.of());
        }

        List<InterestList> existing = interestListRepository
                .findAllByDestination_IdAndReferenceDateBetween(destinationId, rangeStart, rangeEnd);
        List<RecurrenceOccurrenceResponse> occurrences = new ArrayList<>();

        for (LocalDate date = rangeStart; !date.isAfter(rangeEnd); date = date.plusDays(1)) {
            if (!days.contains(date.getDayOfWeek())) continue;

            LocalDate occurrenceDate = date;
            List<InterestList> onDate = existing.stream()
                    .filter(item -> item.getReferenceDate().equals(occurrenceDate))
                    .sorted(Comparator.comparing(InterestList::getId))
                    .toList();
            InterestList samePlan = onDate.stream()
                    .filter(item -> item.getRecurrencePlan() != null && item.getRecurrencePlan().getId().equals(planId))
                    .findFirst().orElse(null);

            if (samePlan != null) {
                occurrences.add(new RecurrenceOccurrenceResponse(date, RecurrenceOccurrenceAction.SKIP,
                        samePlan.getId(), "Already generated by this plan"));
            } else if (!onDate.isEmpty()) {
                occurrences.add(new RecurrenceOccurrenceResponse(date, RecurrenceOccurrenceAction.CONFLICT,
                        onDate.getFirst().getId(), "A demand already exists for this destination and date"));
            } else {
                occurrences.add(new RecurrenceOccurrenceResponse(date, RecurrenceOccurrenceAction.CREATE, null, null));
            }
        }

        int creates = count(occurrences, RecurrenceOccurrenceAction.CREATE);
        int skips = count(occurrences, RecurrenceOccurrenceAction.SKIP);
        int conflicts = count(occurrences, RecurrenceOccurrenceAction.CONFLICT);
        return new RecurrencePreviewResponse(rangeStart, rangeEnd, creates, skips, conflicts, List.copyOf(occurrences));
    }

    private int count(List<RecurrenceOccurrenceResponse> values, RecurrenceOccurrenceAction action) {
        return (int) values.stream().filter(value -> value.action() == action).count();
    }
}
