spring:
  application:
    name: unimove
  datasource:
    url: jdbc:postgresql://localhost:5432/unimove
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: frXtqQ70gJHD12opc47kUT1kBwxhddftEiM3Ky4h/vsCwbHWouddtoHL/JihWhgI3oeVbgXxoHNzSf/Z2zS1Gw==
  expiration: 3600000
  refresh-expiration: 604800000

logging:
  level:
    web: info