package com.guilhermesemog.unimove.model.enums;

public enum AuditAction {
    DEMAND_PUBLISHED,
    DEMAND_UPDATED,
    DEMAND_STATUS_CHANGED,
    TRIP_CREATED,
    TRIP_ASSIGNMENT_CHANGED,
    BOOKING_CREATED,
    BOOKING_REACTIVATED,
    BOOKING_CANCELLED,
    USER_ACTIVATED,
    USER_DEACTIVATED,
    RECURRENCE_PLAN_CREATED,
    RECURRENCE_PLAN_UPDATED,
    RECURRENCE_PLAN_STATUS_CHANGED,
    RECURRENCE_PLAN_ARCHIVED,
    RECURRENCE_PLAN_GENERATED
}
