package com.guilhermesemog.unimove.model.enums;

public enum BusinessEventType {
    BOOKING_CREATED,
    BOOKING_REACTIVATED,
    BOOKING_CANCELLED,
    DEMAND_PUBLISHED,
    DEMAND_UPDATED,
    DEMAND_STATUS_CHANGED,
    TRIP_CREATED,
    TRIP_ASSIGNMENT_CHANGED,
    RECURRENCE_PLAN_CREATED,
    RECURRENCE_PLAN_UPDATED,
    RECURRENCE_PLAN_STATUS_CHANGED,
    RECURRENCE_GENERATION_COMPLETED,
    RECURRENCE_GENERATION_FAILED
}
